# Generated by Django 4.1.1 on 2022-10-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("siwe_auth", "0002_alter_wallet_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "wallet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="siwe_auth.wallet",
                    ),
                ),
                ("address", models.CharField(default=None, max_length=72, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("siwe_auth.wallet",),
        ),
    ]
