# Generated by Django 4.1.1 on 2022-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
