# Generated by Django 4.1.1 on 2022-09-30 23:31

import address.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=address.models.AddressField(unique=True),
        ),
    ]
