# Generated by Django 4.1.7 on 2023-03-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="module_type",
            field=models.CharField(
                choices=[("manager", "Manager"), ("hook", "Hook")],
                default="manager",
                max_length=10,
            ),
        ),
    ]
