# Generated by Django 4.1.7 on 2023-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0002_module_module_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="module_key",
            field=models.CharField(default=None, max_length=128),
        ),
    ]
