# Use node image
FROM node

ARG FONTAWESOME_NPM_AUTH_TOKEN

# Set working directory
WORKDIR /code

# Copy package.json
COPY package.json /code/package.json
COPY package-lock.json /code/package-lock.json

# Load FontAwesome registry
RUN npm config set "@fortawesome:registry" https://npm.fontawesome.com/
RUN npm config set "//npm.fontawesome.com/:_authToken" ${FONTAWESOME_NPM_AUTH_TOKEN}

# Set the auth token
RUN npm install

# Set WATCHBACK_POLLING as true
ENV WATCHBACK_POLLING=true

COPY . /code/