FROM node

ARG NPM_TOKEN
ARG REACT_APP_API_URL

# Set working directory
WORKDIR /code

# Copy package.json
COPY package.json /code/
COPY package-lock.json /code/

# Load FontAwesome registry
RUN npm config set "@fortawesome:registry" https://npm.fontawesome.com/
RUN npm config set "//npm.fontawesome.com/:_authToken" ${NPM_TOKEN}

# Prepare the environment
ENV NODE_OPTIONS=--openssl-legacy-provider
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHBACK_POLLING=true
ENV NODE_ENV=development
ENV WDS_SOCKET_HOST=127.0.0.1

ENV REACT_APP_API_URL=${REACT_APP_API_URL}

# Install the dependencies
RUN npm install

COPY . /code/