# Use node image
FROM node

ARG FONTAWESOME_NPM_AUTH_TOKEN

# Set working directory
WORKDIR /code

# Copy package.json
COPY package.json /code/package.json

# Load FontAwesome registry
RUN npm config set "@fortawesome:registry" https://npm.fontawesome.com/

# Set the auth token
RUN echo "//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" > /code/.npmrc && \
    npm install && \
    rm -f /code/.npmrc

# Set WATCHBACK_POLLING as true
ENV WATCHBACK_POLLING=true

COPY . /code/