# Generated by Django 4.1.7 on 2023-03-11 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import siwe_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("badge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("chain_id", models.IntegerField(default=1337)),
                (
                    "ethereum_address",
                    models.CharField(
                        default=None,
                        max_length=50,
                        validators=[siwe_auth.models.validate_ethereum_address],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("symbol", models.CharField(blank=True, max_length=52, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                ("image_hash", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "contract_uri_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("last_block", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("badges", models.ManyToManyField(blank=True, to="badge.badge")),
                (
                    "delegates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organization_delegates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
