# Generated by Django 4.1.7 on 2023-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="delegates",
        ),
        migrations.AddField(
            model_name="organization",
            name="modules",
            field=models.ManyToManyField(blank=True, to="module.module"),
        ),
    ]
