# Generated by Django 4.1.1 on 2022-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_owner_organization_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
