# Generated by Django 4.1.1 on 2022-09-30 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0003_alter_organization_chain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="delegates",
            field=models.ManyToManyField(
                blank=True,
                related_name="organization_delegates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
