# Generated by Django 4.1.1 on 2022-09-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='users',
            new_name='delegates',
        ),
    ]
