# Generated by Django 4.1.1 on 2022-10-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_organization_contract_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
