# Generated by Django 4.1.1 on 2022-10-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_rename_active_organization_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="contract_address",
            new_name="ethereum_address",
        ),
    ]
