# Generated by Django 4.1.1 on 2022-10-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_rename_contract_address_organization_ethereum_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ethereum", "Ethereum"),
                    ("polygon", "Polygon"),
                    ("optimism", "Optimism"),
                ],
                default="ethereum",
                max_length=50,
            ),
        ),
    ]
