# Generated by Django 4.1.1 on 2022-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='chain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon'), ('Optimism', 'Optimism'), ('Hardhat', 'Hardhat'), ('Gnosis', 'Gnosis')], default='Ethereum', max_length=50),
        ),
    ]
