# Generated by Django 4.1.1 on 2022-10-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_alter_organization_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="symbol",
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
