# Generated by Django 4.1.1 on 2022-10-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0010_organization_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="last_block",
            field=models.IntegerField(default=0),
        ),
    ]
