# Generated by Django 4.1.1 on 2022-10-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_organization_last_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="chain",
            field=models.CharField(
                choices=[
                    ("Ethereum", "Ethereum"),
                    ("Polygon", "Polygon"),
                    ("Optimism", "Optimism"),
                    ("Hardhat", "Hardhat"),
                    ("Localhost", "Localhost"),
                    ("Gnosis", "Gnosis"),
                ],
                default="Polygon",
                max_length=50,
            ),
        ),
    ]
