# Generated by Django 4.1.1 on 2022-10-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0012_alter_organization_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
