# Generated by Django 4.1.1 on 2023-03-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0013_alter_organization_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="chain",
        ),
        migrations.AddField(
            model_name="organization",
            name="chain_id",
            field=models.IntegerField(default=1337),
        ),
    ]
