# Generated by Django 4.1.1 on 2023-03-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_organization_chain_organization_chain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
