# Generated by Django 4.0.6 on 2022-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=4000)),
                ('token_id', models.PositiveIntegerField()),
                ('image_hash', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['token_id'],
            },
        ),
        migrations.CreateModel(
            name='BadgeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=4000)),
                ('image_hash', models.CharField(max_length=256)),
                ('creator_address', models.CharField(max_length=50)),
                ('contract_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(to='badges.badge')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
