# Generated by Django 4.0.6 on 2022-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=4000)),
                ('token_id', models.PositiveIntegerField(default=0)),
                ('image_hash', models.CharField(max_length=256)),
                ('parent_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BadgeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=4000)),
                ('image_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('contract_uri_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('creator_address', models.CharField(max_length=50)),
                ('chain', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='badges.badge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_for', models.ManyToManyField(blank=True, to='badges.badgeset')),
                ('badges_owned', models.ManyToManyField(blank=True, to='badges.badge')),
            ],
        ),
    ]
