# Generated by Django 4.0.6 on 2022-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeset',
            name='badges',
            field=models.ManyToManyField(to='badges.badge'),
        ),
    ]
