# Generated by Django 4.0.6 on 2022-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badgeset_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeset',
            name='contract_uri_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='badgeset',
            name='contract_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='badgeset',
            name='image_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
