# Generated by Django 4.0.6 on 2022-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badgeset_contract_uri_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeset',
            name='chain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
