# Generated by Django 4.0.6 on 2022-07-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgeset_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeset',
            name='contract_initialized',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
