# Generated by Django 4.0.6 on 2022-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_badgeset_contract_initialized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgeset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='badge',
            name='on_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='token_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
