# Generated by Django 4.0.6 on 2022-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_alter_badgeset_options_badge_on_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='parent_address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
