# Generated by Django 4.0.6 on 2022-07-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_badge_parent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-13T19:09:40.216365Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
