# Generated by Django 4.1.1 on 2022-10-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=66, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="balance",
            name="transactions",
            field=models.ManyToManyField(to="balance.transaction"),
        ),
    ]
