# Generated by Django 4.1.1 on 2022-11-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0013_alter_badge_description_alter_badge_image_hash_and_more"),
        ("balance", "0003_remove_balance_balance_balance_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="token_id",
        ),
        migrations.AddField(
            model_name="balance",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="badge.badge",
            ),
        ),
    ]
