# Generated by Django 4.1.1 on 2023-03-06 00:35

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("badge", "0015_remove_badge_account_bound_remove_badge_claimable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("balance", "0004_remove_balance_token_id_balance_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="balance",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="balance",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="transaction",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="balance",
            unique_together={("badge", "user")},
        ),
        migrations.RemoveField(
            model_name="balance",
            name="organization",
        ),
    ]
