# Generated by Django 4.1.1 on 2022-10-01 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="delegates",
            field=models.ManyToManyField(
                blank=True, related_name="delegates", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
