# Generated by Django 4.1.7 on 2023-03-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="delegates",
        ),
    ]
