# Generated by Django 4.1.1 on 2022-09-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
