# Generated by Django 4.1.1 on 2022-09-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('badge', '0002_badge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='delegates',
            field=models.ManyToManyField(related_name='delegates', to='user.user'),
        ),
    ]
