# Generated by Django 4.1.1 on 2022-10-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0003_badge_token_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="token_uri",
            field=models.CharField(default=None, max_length=256),
        ),
    ]
