# Generated by Django 4.1.1 on 2022-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('badge', '0003_badge_delegates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='delegates', to='user.user'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, to='user.user'),
        ),
    ]
