# Generated by Django 4.1.1 on 2022-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0004_alter_badge_delegates_alter_badge_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(),
        ),
    ]
