# Generated by Django 4.1.1 on 2022-10-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0004_alter_badge_token_uri"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
