# Generated by Django 4.1.1 on 2022-09-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_alter_badge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
