# Generated by Django 4.1.1 on 2022-09-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0006_alter_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image_hash',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
