# Generated by Django 4.1.1 on 2022-10-04 02:26

from django.db import migrations, models
import siwe_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0007_badge_signer_ethereum_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="signer_ethereum_address",
            field=models.CharField(
                default=None,
                max_length=50,
                validators=[siwe_auth.models.validate_ethereum_address],
            ),
        ),
    ]
