# Generated by Django 4.1.1 on 2022-10-05 21:26

from django.db import migrations, models
import siwe_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0009_badge_account_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='signer_ethereum_address',
            field=models.CharField(blank=True, default=None, max_length=50, validators=[siwe_auth.models.validate_ethereum_address]),
        ),
    ]
