# Generated by Django 4.1.1 on 2022-10-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badge", "0012_alter_badge_description_alter_badge_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="image_hash",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="token_uri",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
