# Generated by Django 4.1.1 on 2023-01-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0013_alter_badge_description_alter_badge_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='claimable',
            field=models.BooleanField(default=False),
        ),
    ]
