# Generated by Django 4.1.1 on 2023-03-06 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badge", "0014_badge_claimable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="account_bound",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="claimable",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="signer_ethereum_address",
        ),
        migrations.AlterField(
            model_name="badge",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
