# Generated by Django 4.1.1 on 2023-03-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0015_remove_badge_account_bound_remove_badge_claimable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
