# Generated by Django 4.1.7 on 2023-03-11 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badge", "0016_alter_badge_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
