FROM node

# Set working directory
WORKDIR /code

# Copy the requirements file
COPY package.json /code/

# Install the dependencies
RUN npm install

COPY . /code/

# Run the local node
CMD ["npx", "hardhat", "node"]