# Generated by Django 4.1.1 on 2022-10-03 19:34

from django.db import migrations, models
import siwe_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractListener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "ethereum_address",
                    models.CharField(
                        default=None,
                        max_length=50,
                        validators=[siwe_auth.models.validate_ethereum_address],
                    ),
                ),
                ("event", models.CharField(default=None, max_length=50)),
                ("last_block", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
