# Generated by Django 4.1.1 on 2022-10-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractlistener",
            name="event_abi",
            field=models.TextField(default=""),
        ),
    ]
