# Generated by Django 4.1.1 on 2022-10-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_contractlistener_event_abi"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractlistener",
            name="cron_expression",
            field=models.CharField(default="*/2 * * * * *", max_length=50),
        ),
    ]
