# Generated by Django 4.1.1 on 2022-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_contractlistener_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlistener',
            name='chain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon'), ('Optimism', 'Optimism'), ('Hardhat', 'Hardhat'), ('Gnosis', 'Gnosis')], default='Ethereum', max_length=255),
        ),
    ]
