# Generated by Django 4.1.1 on 2022-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_contractlistener_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlistener',
            name='chain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon'), ('Optimism', 'Optimism'), ('Hardhat', 'Hardhat'), ('Localhost', 'Localhost'), ('Gnosis', 'Gnosis')], default='Ethereum', max_length=255),
        ),
    ]
