FROM python:3.9

ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /code

# Copy the requirements file
COPY requirements.txt /code/

# Install the requirements
RUN pip install -r requirements.txt

COPY . /code/